#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-pegdown
Version  : 1.2.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.jar
Source0  : https://repo1.maven.org/maven2/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.jar
Source1  : https://repo1.maven.org/maven2/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-pegdown-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-pegdown package.
Group: Data

%description data
data components for the mvn-pegdown package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.jar
/usr/share/java/.m2/repository/org/pegdown/pegdown/1.2.1/pegdown-1.2.1.pom
